// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SignupTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void signup() {
    driver.get("https://www.demoblaze.com/index.html");
    driver.manage().window().setSize(new Dimension(1074, 618));
    driver.findElement(By.id("signin2")).click();
    driver.findElement(By.id("sign-username")).click();
    driver.findElement(By.id("sign-username")).sendKeys("firaji");
    driver.findElement(By.id("sign-password")).sendKeys("qwertyuiop");
    driver.findElement(By.cssSelector("#signInModal .btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("This user already exist."));
    {
      WebElement element = driver.findElement(By.id("sign-username"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("sign-username")).sendKeys("qafirajitio5");
    {
      WebElement element = driver.findElement(By.id("sign-password"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("sign-password")).sendKeys("qwertyuiop");
    driver.findElement(By.cssSelector("#signInModal .btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Sign up successful."));
    driver.close();
  }
}
